enum ShipmentFulfilmentType {
    PICKUP_AND_DELIVERY = 'PICKUP_AND_DELIVERY',
    DROPSHIPPING = 'DROPSHIPPING',

    RETURN_ORDER = 'RETURN_ORDER',

    EXCHANGE_ORDER = 'EXCHANGE_ORDER',

    REPAIR_ORDER = 'REPAIR_ORDER',
}

export default ShipmentFulfilmentType;